#!/bin/bash

GITSTATUS=`git status --porcelain 2> /dev/null`
GITSHA=`git rev-parse HEAD`

docker build -t log-daddy .
if [[ $GITSTATUS == "" ]]; then
    docker tag log-daddy quay.io/joeatwork/log-daddy:$(GITSHA)
    docker push quay.io/joeatwork/log-daddy
else
    echo "(Don't push to quay, we're still working on it)" >&2
fi
